apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mysql.name }}-configmap
data:
  MYSQL_ROOT_PASSWORD: "{{ .Values.mysql.env.MYSQL_ROOT_PASSWORD }}"
  MYSQL_ALLOW_EMPTY_PASSWORD: "{{ .Values.mysql.env.MYSQL_ALLOW_EMPTY_PASSWORD }}"
  MYSQL_USER: "{{ .Values.mysql.env.MYSQL_USER }}"
  MYSQL_PASSWORD: "{{ .Values.mysql.env.MYSQL_PASSWORD }}"
  MYSQL_DATABASE: "{{ .Values.mysql.env.MYSQL_DATABASE }}"
