apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic
spec:
        #type: NodePort     
  selector:
    app: spring-petclinic
  ports:
  - protocol: TCP
    port: {{ .Values.webapp.sport }}
    targetPort: {{ .Values.webapp.port }}
    #nodePort: 31000
