apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.mysql.name }}
  labels:
    app: {{ .Values.mysql.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers: 
      - name: {{ .Values.mysql.name }}
        image: {{ .Values.mysql.repo }}/{{ .Values.mysql.image }}:{{ .Values.mysql.tag }}
        ports:
        - containerPort: {{ .Values.mysql.port }}
        envFrom:
          - configMapRef:
              name: {{ .Values.mysql.name }}-configmap
